# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 746ca4a7c74b75a0337a954bd8f40b9c065f11e5249c0dcf6057d57d1e6c4f8cc749f03638a8377fbe604bb267b4d429d7ef8659dcd4d67a1bcf895544ea6e91

test:
  secret_key_base: 3671ad909371fe14fe47a2ab8ef55dcf88aeffeed5f055059092c3b870cfee777b0642e15a43b3addb549e28c27c9153e07a8bd066aab34b30aea7e63f8971b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
